services:
  php:
    build:
      context: ./docker/php
    ports:
      - "${PHP_PORT:-8081}:80"
    volumes:
      - ./:/var/php
    working_dir: /var/php
    command: php -S 0.0.0.0:80 -t ./public

  database:
    image: mariadb:latest
    restart: always
    volumes:
      - ./create_db.sql:/docker-entrypoint-initdb.d/create_db.sql
    working_dir: /var/lib/mysql
    env_file:
      - .env

  adminer:
    image: adminer
    restart: always
    ports :
      - "8082:8080"